### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by natsumerinchan** [supremegamers/vendor_intel_proprietary_houdini#1]
I'm trying to build Android-x86 ( r-x86 branch ) with WSA houdini.
After entered these commands:

```
mkdir Android-x86
cd Android-x86
repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b r-x86
repo sync --no-tags --no-clone-bundle
git clone -b wsa https://github.com/supremegamers/vendor_intel_proprietary_houdini.git houdini
```

Add `$(call inherit-product-if-exists,vendor/houdini/houdini.mk)` to device/generic/common/device.mk

```
source build/envsetup.sh
lunch android_x86_64-userdebug
m -j6 rpm
```

I get the following error:

```
[ 86% 95854/110742] Install: out/target/product/x86_64/system/lib64/libnb.so
FAILED: out/target/product/x86_64/system/lib64/libnb.so
/bin/bash -c "(rm -f out/target/product/x86_64/system/lib64/libnb.so ) && (cp out/target/product/x86_64/obj/SHARED_LIBRARIES/libnb_intermediates/libnb.so out/target/product/x86_64/system/lib64/libnb.so ) && (rm -rf out/target/product/x86_64/system/{bin,lib}/{arm*,*houdini*} {out/target/product/x86_64/system,out/target/product/x86_64}/vendor/{bin,lib}/{arm*,*houdini*}; mkdir -p out/target/product/x86_64/system/{lib/arm,lib64/arm64}; touch out/target/product/x86_64/system/lib/libhoudini.so out/target/product/x86_64/system/lib64/libhoudini.so )"
touch: 'out/target/product/x86_64/system/lib64/libhoudini.so': No such file or directory
01:44:27 ninja failed with: exit status 1

#### failed to build some targets (04:06:42 (hh:mm:ss)) ####
```

How should I solve it?

**Comment by hmtheboy154** [comment]
First remember to inherit more files than just houdini.mk
https://github.com/supremegamers/device_generic_common/commit/e4f3b23aa2042a27607e31d15367978e0fae29a2

Then nuke nativebridge in device/generic/common
https://github.com/supremegamers/device_generic_common/commit/553b43cff47bb72dd712589a6744be8f173c9d8e

**Comment by natsumerinchan** [comment]
> First remember to inherit more files than just houdini.mk [supremegamers/device_generic_common@e4f3b23](https://github.com/supremegamers/device_generic_common/commit/e4f3b23aa2042a27607e31d15367978e0fae29a2)
> 
> Then nuke nativebridge in device/generic/common [supremegamers/device_generic_common@553b43c](https://github.com/supremegamers/device_generic_common/commit/553b43cff47bb72dd712589a6744be8f173c9d8e)

Thanks for your help, I'll try to build it again now.
